### PR TITLE
Add nocturnal

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@peterbe r?

**Comment by peterbe** [comment]
@glogiotatidis you don't have to r? these kinds of things. I trust you :)

**Comment by glogiotatidis** [comment]
@peterbe thanks for trusting me but I don't have write rights on this repo! :)

**Comment by peterbe** [comment]
@glogiotatidis which team are you part of? I'll add that team.

**Comment by peterbe** [comment]
fyi https://github.com/mozilla/contribute.json/commit/8d1df69ae00bc5b35eea05df1e040dc78f4ab0b8

**Pull request merged**
