### PR TITLE
switch to ui-router

### PR DESCRIPTION
**Pull request by peterbe**
ui-router is so much better.

### CODE REVIEW

**Comment by peterbe** [comment]
@Osmose r?

**Comment by peterbe** [comment]
or @pmclanahan r?

**Comment by pmclanahan** [comment]
/me knows nothing about Angular. I'll just take your word for it that this is better :)

**Comment by Osmose** [comment]
I too know little about Angular and ui-router, but your changes make sense and look good to me. If it works and you're not worried about doing it wrong I'd say this is r+ from me. :D

**Pull request merged**
