### PR TITLE
Upgrade to heroku-20 stack

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
This should allow building the Heroku app on the `heroku-20` stack

**Comment by pmac** [comment]
Oh wow! Thanks @jbuck!. I was just trying to find some time to look at this.

**Comment by jbuck** [comment]
Fingers crossed it works!

**Comment by jbuck** [comment]
@pmac would you be able to review+merge?

**Comment by pmac** [comment]
Merged, but now we need to set the new stack and try to deploy, right?

**Pull request merged**
